---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.4
  - name: ubuntu-14.10

suites:
  - name: default
    run_list:
      - recipe[chef_monit::default]
      - recipe[chef_monit::ssh]
    attributes:
